Sources/MockoloFramework/Models/ParsedEntity.swift
Sources/MockoloFramework/Operations/Generator.swift
Sources/MockoloFramework/Operations/OutputWriter.swift
Sources/MockoloFramework/Operations/ProcessedTypeMapGenerator.swift
Sources/MockoloFramework/Operations/ProtocolMapGenerator.swift
Sources/MockoloFramework/Operations/UniqueModelGenerator.swift
Sources/MockoloFramework/Utils/InheritanceResolver.swift
Tests/TestOverloads/FixtureFuncOverload1.swift

With SwiftSyntax, we no longer need to parse import lines manually, but can just keep track of filepaths that are relevant and look up the imported lines given the path later.

Update imports with swiftsyntax parse results

---

install-script.sh

Distributing mockolo now requires shipping with lib_InternalSwiftSyntaxParser.dylib due to the use of the latest SwiftSyntax (from swift 5.1). This script handles build/install requirements.

Add a build/install script for distribution

---

Sources/MockoloFramework/Models/MethodModel.swift
Sources/MockoloFramework/Templates/ClosureTemplate.swift
Sources/MockoloFramework/Utils/StringExtensions.swift
Sources/MockoloFramework/Utils/TypeParser.swift
Tests/TestNonSimpleVars/FixtureNonSimpleFuncs.swift
Tests/TestNonSimpleVars/NonSimpleCaseTests.swift

Fixes an issue where generated mock code using the name for as a closure argument to a function. These changes make sure to correctly escape for in this situation and with other closure keyword arguments

Fix for `for` named closure params

---

README.md
Sources/Mockolo/Executor.swift
Sources/MockoloFramework/Operations/Generator.swift
Sources/MockoloFramework/Operations/OutputWriter.swift
Sources/MockoloFramework/Utils/InheritanceResolver.swift
Sources/MockoloFramework/Utils/StringExtensions.swift
Tests/MockoloTestCase.swift
Tests/TestTestableImportStatements/FixtureTestableImportStatements.swift
Tests/TestTestableImportStatements/TestableImportStatementsTests.swift

Adds the ability to add @testable import statements via the -i flag. This is useful for users who want to only add their mocks to a project's Test target and use the @testable import functionality to import the main projects target

Adds ability to add @testable import statements

---

Sources/MockoloFramework/Utils/Logger.swift

Needed a little tweak as setting `.warning` or `.error` did not take effect, and the logger still printed all the calls.

Tweak the log function to ensure it respects the log level

---

Sources/MockoloFramework/Utils/Logger.swift

Resolves https://github.com/uber/mockolo/issues/93
Ensures `verbose` log level prints out more details than `info`. Updated signpost methods to be active only when `verbose` log level is used.  Signpost traces will not be collected for `info`, `warn`, and `error` levels.
I just realized that the current order is consistent with `OSLogType`, but that has been addressed in SwiftLog https://github.com/apple/swift-log/blob/master/Sources/Logging/Logging.swift which seems to be more aligned with loggers available in other languages (i.e. log4j in Java https://en.wikipedia.org/wiki/Log4j).
Signed-off-by: Marcin Iwanicki <marcin@iwanicki.me>

Update order of log levels

---

Package.swift

Since SwiftSyntax released `0.50200.0` for Xcode 11.4 [yesterday](https://github.com/apple/swift-syntax/releases/tag/0.50200.0), building mockolo in a clean environment started to fail with Xcode 11.3.x, as the version of SwiftSyntax is not pinned.
```
› xcode-select -s /Applications/Xcode_11_3_1.app
› rm -rf Package.resolved .build
› swift build
Fetching https://github.com/apple/swift-package-manager.git
(...)
Completed resolution in 38.32s
Cloning https://github.com/apple/swift-syntax.git
Resolving https://github.com/apple/swift-syntax.git at 0.50200.0
(...)
```
This change pins and changes the version of SwiftSyntax for the language version, leads to successful build with Xcode 11.3.x.
```
› xcode-select -s /Applications/Xcode_11_3_1.app
› rm -rf Package.resolved .build
› swift build …
```

Use exact and appropriate versions of SwiftSyntax

---

Sources/MockoloFramework/Models/ClosureModel.swift
Sources/MockoloFramework/Models/MethodModel.swift
Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift
Sources/MockoloFramework/Templates/MethodTemplate.swift
Sources/MockoloFramework/Utils/StringExtensions.swift
Sources/MockoloFramework/Utils/TypeParser.swift
Tests/TestNonSimpleCases/FixtureNonSimpleFuncs.swift
Tests/TestNonSimpleCases/NonSimpleCaseTests.swift

Currently Mockolo is broken for Protocols that return Self. These changes ensure that we return the mock class type when we encounter a Self return type:
Example protocol that breaks Mockolo currently
```
/// @mockable
protocol NonSimpleFuncs {
@discardableResult
func returnSelf() -> Self
}
```

[ReturnSelf] Allows Protocols to Return Self

---

README.md

Installation via _Homebrew_ requires _Xcode 11.4_ on the local machine. Seems like it was updated in [1.2.3](https://github.com/uber/mockolo/releases/tag/1.2.3) on June 9.

Update requirements in Readme

---

Sources/MockoloFramework/Templates/ClosureTemplate.swift
Sources/MockoloFramework/Utils/StringExtensions.swift
Tests/TestGenericFuncs/FixtureGenericFunc.swift

Adds logic to handle a situation where we have a generic optional closure that the handler must cast to execute in the mock

[#119] Attempts to fix Optional Generic Closures

---

Sources/Mockolo/Executor.swift

Changes the help message for `--exclude-imports` from
`If set, listed modules will be exluded from the import statements in the mock output.` 
to
`If set, listed modules will be excluded from the import statements in the mock output.`

Fixes small typo in help message

---

Sources/MockoloFramework/Models/ArgumentsHistoryModel.swift
Tests/TestArgumentsHistory/ArgumentsHistoryTests.swift
Tests/TestArgumentsHistory/FixtureArgumentsHistory.swift

Changed to exclude Closure defined by typealias when creating ArgumentHistoryCapturable.
Currently, if Closure defined by typealias is in the argument, a Mock will be created as shown below and a compile error will occur.
```swift
typealias FooHandler = () -> Int
/// @mockable
protocol Foo {
func fooFunc(handler: @escaping FooHandler)
}
class FooMock: Foo {
~
var fooFuncArgValues = [@escaping FooHandler]() // <- error
func fooFunc(handler: @escaping FooHandler) {
}
~
}
```

Exclude escaping typealias handler from argument history capture.

---

Sources/MockoloFramework/Operations/OutputWriter.swift
Tests/TestFuncs/TestBasicFuncs/FuncBasicTests.swift
Tests/TestOutputChange/OutputChangeTests.swift

Resolves: #131 
As proposed in #131, this PR adapts the `write` method to only write the destination file if its content did not change. ~In the [equivalent PR](https://github.com/uber/needle/pull/382) for `needle` I was able to add a unit test for the file write behavior, but `mockolo` doesn't depend on https://github.com/uber/swift-common, so I wasn't able to leverage the `UnitTestLogger`. Do you have any other ideas of how to test the file write behavior?~
**Update:**
I also added a test that compares the [`.creationDate`](https://developer.apple.com/documentation/foundation/fileattributekey/1418187-creationdate) and [`.modificationDate`](https://developer.apple.com/documentation/foundation/fileattributekey/1410058-modificationdate) when calling `write` repeatedly. If you have any …

Avoid writing to destination file if content is unchanged

---

Sources/MockoloFramework/Templates/VariableTemplate.swift
Tests/TestClassMocking/FixtureMockableClass.swift
Tests/TestClassMocking/FixtureMockableClassInit.swift

When a stored property is overridden with both:
- assigning default value
- attaching property observers (willSet/didSet)
that leads to the compile error of "Variable with getter/setter cannot have an initial value".
ref: https://stackoverflow.com/a/33641878/3068179
> Looks like this doesn't work when overriding inherited properties. Here is an example of what you can't do:
```swift
class StepWihtoutCounter {
var totalSteps: Int = 0 
}
class StepCounter: StepWihtoutCounter {
override var totalSteps: Int = 0 {
willSet(newTotalSteps) {
print("About to set totalSteps to \(newTotalSteps)")
}
didSet {
if totalSteps > oldValue  {
print("Added \(totalSteps - oldValue) steps")
}
}
}
}
```

Fix class mock variable generation

---

Package.swift

- close #142 
- https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-release-notes
> Swift packages that specify a 5.4 tools version can now explicitly declare targets as executable, which allows the use of the @main keyword in package code. ([SE-0294](https://forums.swift.org/t/se-0294-declaring-executable-targets-in-package-manifests/42404), 47691185)

Support Swift 5.4

---

Package.swift

When I add Mockolo to a package, I get the following error:
```
Dependencies could not be resolved because package 'mockolo' is required using a stable-version but 'mockolo' depends on an unstable-version package 'swift-syntax' and root depends on 'mockolo' 1.4.0.
```
We can solve this problem by adding SwiftSyntax as described in its README.  
ref: https://github.com/apple/swift-syntax#declare-swiftpm-dependency-with-release-tag

Add SwiftSyntax as described in the README

---

Package.swift

Remove Swift Argument Parser since it is not used.
It is preferable to replace swift-tools-support-core in the future.
- https://github.com/apple/swift-argument-parser/issues/5
- https://github.com/apple/swift-tools-support-core/pull/194

Remove Swift Argument Parser since it is not used.

---

Package.swift
Sources/Mockolo/Executor.swift
Sources/Mockolo/main.swift
Sources/MockoloFramework/Operations/Generator.swift
Sources/MockoloFramework/Parsers/SourceParser.swift
Sources/MockoloFramework/Utils/StringExtensions.swift
Tests/MockoloTestCase.swift

Resolves #148 
- Replace swift-tools-support-core deprecated ArgumentParser with swift-argument-parser
- Give loggingLevel and annotation default levels via ArgumentParser
- Move some validation logic to Executor.validate
- Make destination a required option
- Add validation for logging levels
I am unsure about unit testing these changes. I think stubbed functions for `generate` and `fullPath` would need to be injected into `Executor`, but those break synthesized Decodable conformance which is a require for implementers of `ParsableCommand`..

Replace ArgumentParser with swift-argument-parser

---

.github/workflows/builds.yml
Package.swift

- Update SwiftSyntax
- Support Swift 5.4.2 and 5.5 in CI
- https://github.com/apple/swift-syntax/releases/tag/0.50500.0
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
- https://github.com/yonaskolb/XcodeGen/blob/12511afed82a3db1a9dbd814e835920c98d9914e/.github/workflows/ci.yml

Update SwiftSyntax and support Swift 5.4.2 and 5.5 in CI

---

README.md
Sources/Mockolo/Executor.swift

Resolves #172 
This PR updates the parsing strategy for all `[String]` options to `upToNextOption`, which will restore the functionality of passing multiple strings separated by space to via one option, e.g. `-mock path/to/foo path/to/bar`

Update array parsing strategy

---

Package.swift

Occur warnings when opening this project by Xcode or building.
These files are unneeded for build so exclude in Package.swift.
```
found 2 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
/Sources/MockoloFramework/README.txt
/Sources/MockoloFramework/LICENSE.txt
```
- Xcode 13.2.1 (13C100)

Fix warnings of unhandled files in MockoloFramework

---

.github/workflows/builds.yml
Package.swift
Sources/MockoloFramework/Parsers/SourceParser.swift
Sources/MockoloFramework/Parsers/SwiftSyntaxExtensions.swift

- Added Swift 5.6 support to solve the problem of failing to generate mocks in Xcode 13.3
- I have not added CI execution in Swift 5.6 because GitHub-hosted runners in github actions does not currently support macOS 12

Support Swift 5.6

---

Package.swift

SwiftSyntax has released to resolve https://bugs.swift.org/browse/SR-15989, so I specified to `.exact("0.50600.1")`.
related: https://github.com/uber/mockolo/pull/178 fyi @aroshipup

Bump SwiftSyntax to exact 0.50600.1 in Swift 5.6

---

Sources/MockoloFramework/Parsers/SourceParser.swift
Sources/MockoloFramework/Parsers/SwiftSyntaxExtensions.swift

These names have changed over time,
therefore we must allow for either
name to be imported

Handle varying names for SyntaxParser

---

Sources/MockoloFramework/Operations/Generator.swift
Sources/MockoloFramework/Operations/OutputWriter.swift
Tests/MockoloTestCase.swift
Tests/TestOutputChange/OutputChangeTests.swift
Tests/TestThrowingErrors/ThrowingErrorsTests.swift

Close #189 
This PR makes mockolo command report error in log message and finish with non-zero exit code when it fails to create mock file. Change of the log message for that situation is shown below.
```
❯ mockolo --sourcedirs Path/To/SourceDir --destination /NonexistentDirectory/Mocks.swift
Start...
["Process input mock files..."]
["Took", 4.1961669921875e-05]
["Process source files and generate an annotated/protocol map..."]
["Took", 0.023231029510498047]
["Resolve inheritance and generate unique entity models..."]
["Took", 0.0008450746536254883]
["Render models with templates..."]
["Took", 0.0002319812774658203]
["Write the mock results and import lines to", "/NonexistentDirectory/Mocks.swift"]
["Took", 0.0001609325408935547]
["TOTAL", 0.024510979652404785]
["#Protocols = 3, …
```

Report error when fails to write mock file

---

Package.swift

I updated package [swift-tools-support-core](https://github.com/apple/swift-tools-support-core) from 0.2.3 to 0.2.7 because I can't build mockolo with Xcode 14 beta 5 with swift-tools-support-core 0.2.3. 
The origin of compiling error is [here](https://github.com/apple/swift-tools-support-core/blob/main/Sources/TSCUtility/FSWatch.swift#L848) and I attached the error.
This issue is fixed  in https://github.com/apple/swift-tools-support-core/pull/345 . which is included in version 0.2.7.
That's why I updated swift-tools-support-core version in mockolo from 0.2.3 to 0.2.7.
----
This issue was clarified thanks to @sidepelican and @omochi :pray:

Updated swift-tools-support-core version from 0.2.3 to 0.2.7

---

.github/workflows/release.yml
install-script.sh

https://github.com/uber/mockolo/releases/download/1.7.0/mockolo.tar.gz only includes arm64 architecture:
```
$ file mockolo
mockolo: Mach-O 64-bit executable arm64
```
The prebuilt binary should have both x86_64 and arm64 architecutres.

Make universal binary

---

Package.swift

* #178 added Swift 5.6 support, but f38ae33 limited the version flexibility of the swift-argument-parser dependency. The reasoning for this is explained in [this comment](https://github.com/uber/mockolo/pull/178#issuecomment-1071918213).
* This makes package resolution for other packages that have Mockolo as a dependency less flexible. So, to have the same flexibility as before f38ae33, but still account for the issue mentioned in the comment linked above, the version range of the  swift-argument-parser dependency is being made dependent on the Swift version.

Update swift-argument-parser dependency

---

.github/workflows/builds.yml
.github/workflows/release.yml
Package.swift

- https://github.com/apple/swift-syntax/releases/tag/0.50700.0
- https://github.com/apple/swift-syntax/releases/tag/0.50700.1

Bump swift-syntax for Swift 5.7

---

Sources/Mockolo/Executor.swift

Mockolo command line argument for customImports changed where -c shorthand was removed.
Previously, you could use either --custom-imports OR -c:
https://github.com/uber/mockolo/blob/d5f08f5e03bfc25f88adbe5bcab684ad2f25b45c/Sources/Mockolo/Executor.swift#L113-L114
But now only --custom-imports:
https://github.com/uber/mockolo/blob/master/Sources/Mockolo/Executor.swift#L41-L43
This occurred on https://github.com/uber/mockolo/pull/153 but there is no explicit mention of this change so hoping we can add it back so folks do not need to update their existing cli scripts.

Add customImports command shorthand back

---

Sources/Mockolo/Executor.swift

These are info level logs that should not appear at this log level

Disable Start/done logs when log level is 3

---

Sources/MockoloFramework/Parsers/SwiftSyntaxExtensions.swift
Tests/TestOverloads/FixtureInheritance.swift
Tests/TestOverloads/OverloadTests.swift

When use `&` keyword to conform to multiple protocols, mockolo only picks up the first protocol.
This issue is already mentioned in #170 
- target mockable
```swift
protocol FirstSwiftProtocol {
var someBool: Bool { get }
func doSomething()
}
protocol SecondSwiftProtocol {
var someInt: Int { get set }
func doSomethingElse() -> Bool
}
/// @mockable
protocol TestProtocol: FirstSwiftProtocol & SecondSwiftProtocol {
func doSomethingSpecial()
}
```
- Output mock (members in `SecondSwiftProtocol` are not implemented.)
```swift
///
/// @Generated by Mockolo
///
class TestProtocolMock: TestProtocol {
init() { }
init(someBool: Bool = false) {
self.someBool = someBool
}
private(set) var someBoolSetCallCount = 0
var someBool: Bool = false { didSet { someBoolSetCallCount += 1 } }
private(set) var …
```

Support type composition (`&` keyword)

---

install-script.sh

One of the install option; downloading mockolo.tar.gz does not work if  we generate mockolo binary with`lib_InternalSwiftSyntaxParser` which is placed inside Xcode toolchain.
I think there is no need to copy `lib_internalSwiftSyntaxParser.dylib` from xcode toolchain and we can just use one resolved by running `swift build`.
please feel free to correct me if there is a better way.
- close #219

Use lib_InternalSwiftSyntaxParser resolved by SPM

---

.github/workflows/builds.yml
Package.swift
README.md

To support building homebrew bottle on macOS 12, set swift-tools-version to 5.7.
(The latest Xcode that macOS11 can use is 13.2.1, and it is too old so I give up.

Add support to build on macOS 12

---

Sources/MockoloFramework/Models/ArgumentsHistoryModel.swift
Sources/MockoloFramework/Models/ClosureModel.swift
Sources/MockoloFramework/Models/MethodModel.swift
Sources/MockoloFramework/Models/ParsedEntity.swift
Sources/MockoloFramework/Utils/SequenceExtensions.swift

This is simple cleaning PR.
With the [SE-0249](https://github.com/apple/swift-evolution/blob/main/proposals/0249-key-path-literal-function-expressions.md), some extensions can get be useable without it.

Drop legacy sequence extensions

---

Sources/MockoloFramework/Models/MethodModel.swift
Sources/MockoloFramework/Utils/StringExtensions.swift
Tests/TestFuncs/TestGenericFuncs/FixtureGenericFunc.swift
Tests/TestFuncs/TestGenericFuncs/GenericFuncTests.swift

A mock file will fail to compile if the protocol being mocked contains two functions with the same signature and name but has different generic constraints. Consider the following example:
```
@CreateMock
protocol Foo {
func connect<T>(adapter: T) where T: Adapter
func connect<T>(adapter: T) where T: KeyedAdapter
}
```
The above code will generate the following mock:
```
public var connectCallCount = 0    
public var connectHandler: ((Any) -> ())?    
public func connect<T>(adapter: T)  where T: Adapter {
mockFunc(&connectCallCount)("connect", connectHandler?(adapter), .void)    
}
```
This fails to compile because it's missing the implementation with `KeyedAdapter`. With this PR, the following mock will now be produced
```
public var connectCallCount = 0
public var connectHandler: ((Any) …
```

[Bugfix] Fix functions with same signature and different generic constraints not getting generated

---

Sources/MockoloFramework/Operations/Generator.swift
Sources/MockoloFramework/Operations/ImportsHandler.swift

- There's no need to include all the imports we see.
- Fixes #242

Only consider relevant files when collecting import statements.

---

Package.swift
Sources/MockoloFramework/Models/ParsedEntity.swift
Sources/MockoloFramework/Operations/Generator.swift
Sources/MockoloFramework/Parsers/SwiftSyntaxExtensions.swift
Sources/MockoloFramework/Utils/StringExtensions.swift

The codebase is being updated to work with swift-syntax 509.0.0

Update swift-syntax to 509.0.0

---

Sources/MockoloFramework/Version.swift

The latest [release](https://github.com/uber/mockolo/releases/tag/2.0.1) of Mockolo has the old version `2.0.0`. It's a minor PR that aims to sync the version w.r.t to release.

Fix the version code concerning release

---

Sources/MockoloFramework/Models/ClassModel.swift
Sources/MockoloFramework/Models/ParsedEntity.swift
Sources/MockoloFramework/Operations/UniqueModelGenerator.swift
Sources/MockoloFramework/Parsers/SwiftSyntaxExtensions.swift
Sources/MockoloFramework/Templates/ClassTemplate.swift
Sources/MockoloFramework/Utils/InheritanceResolver.swift
Sources/MockoloFramework/Utils/StringExtensions.swift
Tests/TestSendable/FixtureSendable.swift
Tests/TestSendable/SendableTests.swift

I have implemented the enhancements proposed in issue https://github.com/uber/mockolo/issues/252.
For mock classes that are required to conform to the `Sendable` protocol, I have made them inherit from `@unchecked Sendable`. This change should help reduce the number of unnecessary compiler warnings.
```swift
Source
protocol SendableProtocol: Sendable {}
class UncheckedSendableClass: @unchecked Sendable {}
final class SendableClass: Sendable {}
```
```swift
Output
class SendableProtocolMock: SendableProtocol, @unchecked Sendable {}
class UncheckedSendableClassMock: UncheckedSendableClass, @unchecked Sendable {}
// final class SendableClass is skipped, because final class can't make a mock class.
```
| Before | After |
| --- | --- |
| <img …

Support `Sendable` compliant protocols and classes

---

Package.swift

Update swift-syntax.
No codebase changes were necessary.

Update swift-syntax 510

---

.github/workflows/builds.yml
.github/workflows/release.yml
README.md
bundle/info.json
bundle/make_artifactbundle.sh
install-script.sh

Issue: https://github.com/uber/mockolo/issues/246
Add an artifact bundle to use as a build tools plugin.
This PR includes GitHub Actions to build for each architecture on Linux and macOS, and package them into an artifact bundle. Additionally, it documents the steps to use it as a build tools plugin in the README.md.

Add artifactbundle for build tools plugin

---

.github/workflows/release.yml
Sources/MockoloFramework/Version.swift

Sorry, I have failed to release the latest version.
https://github.com/uber/mockolo/actions/runs/8795885150
No codebase changes, but I’m not sure about rerunning the release job on the `2.1.0` tag, so I suggest updating the patch version.
The updated job is tested at https://github.com/sidepelican/mockolo/actions/runs/8796562718 .

Fix release ci

---

Sources/MockoloFramework/Utils/TypeParser.swift
Tests/TestFuncs/TestOpaqueTypeFuncs/FixtureOpaqueTypeFunc.swift
Tests/TestFuncs/TestOpaqueTypeFuncs/OpaqueTypeFuncTests.swift

The following code:
```
protocol ProtocolReturningOpaqueTypeInClosureProtocol {
func register(router: @autoclosure @escaping () -> (some Error))
}
```
produces this mock:
```
class ProtocolReturningOpaqueTypeInClosureProtocolMock: ProtocolReturningOpaqueTypeInClosureProtocol {
init() { }
private(set) var registerCallCount = 0
var registerHandler: ((@autoclosure @escaping () -> (some Error)) -> ())?
func register(router: @autoclosure @escaping () -> (some Error))  {
registerCallCount += 1
if let registerHandler = registerHandler {
registerHandler(router())
}
}
}
```
causing the compilation error:
`'some' cannot appear in parameter position in result type '((@autoclosure @escaping () -> (some Error)) -> ())?'`
This pr fixes the variable `registerHandler` by generating the following mock: …

Compilation fix for a mock where the return type of a closure is an opaque type

---

.github/workflows/release.yml
bundle/info-macos.json
bundle/info.json
bundle/make_artifactbundle.sh
install-script.sh

Currently, the mockolo binary for aarch64 on Ubuntu is built on an x86_64 machine using Docker and qemu, which is extremely slow.
With the release of [Static Linux SDK](https://www.swift.org/documentation/articles/static-linux-getting-started.html) in Swift 6, we can speed up the build process for aarch64 Linux.
In the GitHub Actions for the release build, we install the Static Linux SDK and use it. 
As a result, the size of the artifact bundle has increased. To address this, we provide a lightweight artifact bundle without Linux support for users who only use mockolo on macOS.
Since the Static Linux SDK uses musl, mockolo will be able to run on more Linux distributions. However, we do not have a strong motivation to actively support these additional distributions, so this is more of a …

Speed up aarch64 builds using Static Linux SDK

---

Sources/MockoloFramework/Models/ArgumentsHistoryModel.swift
Sources/MockoloFramework/Models/ClassModel.swift
Sources/MockoloFramework/Models/ClosureModel.swift
Sources/MockoloFramework/Models/IfMacroModel.swift
Sources/MockoloFramework/Models/MethodModel.swift
Sources/MockoloFramework/Models/Model.swift
Sources/MockoloFramework/Models/NominalModel.swift
Sources/MockoloFramework/Models/ParamModel.swift
Sources/MockoloFramework/Models/ParsedEntity.swift
Sources/MockoloFramework/Models/TypeAliasModel.swift
Sources/MockoloFramework/Models/VariableModel.swift
Sources/MockoloFramework/Operations/Generator.swift
Sources/MockoloFramework/Operations/UniqueModelGenerator.swift
Sources/MockoloFramework/Templates/ClassTemplate.swift
Sources/MockoloFramework/Templates/ClosureTemplate.swift
Sources/MockoloFramework/Templates/MethodTemplate.swift
Sources/MockoloFramework/Templates/NominalTemplate.swift
Sources/MockoloFramework/Templates/ParamTemplate.swift
Sources/MockoloFramework/Templates/TypeAliasTemplate.swift
Sources/MockoloFramework/Templates/VariableTemplate.swift
Sources/MockoloFramework/Utils/StringExtensions.swift
Sources/MockoloFramework/Utils/TypeParser.swift
Tests/MockoloTestCase.swift
Tests/TestActor/ActorTests.swift
Tests/TestActor/FixtureActor.swift

https://github.com/uber/mockolo/issues/216
When the mock inherits the `Actor` protocol, the mock becomes `actor` automatically.

Add support for `Actor` protocol.

---

Sources/MockoloFramework/Models/ArgumentsHistoryModel.swift
Sources/MockoloFramework/Models/ClosureModel.swift
Sources/MockoloFramework/Models/MethodModel.swift
Sources/MockoloFramework/Models/ThrowingKind.swift
Sources/MockoloFramework/Models/VariableModel.swift
Sources/MockoloFramework/Parsers/SwiftSyntaxExtensions.swift
Sources/MockoloFramework/Templates/ClosureTemplate.swift
Sources/MockoloFramework/Templates/MethodTemplate.swift
Sources/MockoloFramework/Templates/NominalTemplate.swift
Sources/MockoloFramework/Templates/ThrowingKindTemplate.swift
Sources/MockoloFramework/Templates/VariableTemplate.swift
Sources/MockoloFramework/Utils/StringExtensions.swift
Sources/MockoloFramework/Utils/TypeParser.swift
Tests/TestActor/FixtureActor.swift
Tests/TestCombine/FixtureCombine.swift
Tests/TestExistentialAny/FixtureExistentialAny.swift
Tests/TestFuncs/TestBasicFuncs/FixtureNonSimpleFuncs.swift
Tests/TestModifiersTypes/FixtureModifiersTypes.swift
Tests/TestModuleNames/FixtureModuleOverrides.swift
Tests/TestOverloads/FixtureDuplicates4.swift
Tests/TestOverloads/FixtureInheritance.swift
Tests/TestPATs/FixturePAT.swift
Tests/TestRx/FixtureRxVars.swift
Tests/TestVars/FixtureAsyncThrowsVars.swift
Tests/TestVars/FixtureNonSimpleVars.swift
Tests/TestVars/VarTests.swift

- https://github.com/uber/mockolo/issues/210
Supported `{ get async throws }`.
```swift
/// @mockable
protocol AsyncThrowsVars {
var getAndThrows: MyValue { get throws }
var getAndAsync: MyValue { get async }
var getAndAsyncAndThrows: Int { get async throws(any Error) }
}
```
- Generated
```swift
class AsyncThrowsVarsMock: AsyncThrowsVars {
init() { }
init(getAndThrows: MyValue, getAndAsync: MyValue, getAndAsyncAndThrows: Int = 0) {
self.getAndThrowsHandler = { getAndThrows }
self.getAndAsyncHandler = { getAndAsync }
self.getAndAsyncAndThrowsHandler = { getAndAsyncAndThrows }
}
var getAndThrowsHandler: (() throws -> MyValue)?
var getAndThrows: MyValue {
get throws {
if let getAndThrowsHandler = getAndThrowsHandler {
return try getAndThrowsHandler()
}
fatalError("getAndThrowsHandler …
```

Add async and throwing property support

---

Tests/TestClassMocking/FixtureMockableClass.swift

The issue in https://github.com/uber/mockolo/issues/245 was secondarily solved by https://github.com/uber/mockolo/pull/267 .
This PR adds tests for the case described in issue #245.

Add test for read-only computed property in class

---

Package.resolved
Package.swift
Sources/MockoloFramework/Models/ArgumentsHistoryModel.swift
Sources/MockoloFramework/Models/ClosureModel.swift
Sources/MockoloFramework/Models/IfMacroModel.swift
Sources/MockoloFramework/Models/MethodModel.swift
Sources/MockoloFramework/Models/Model.swift
Sources/MockoloFramework/Models/NominalModel.swift
Sources/MockoloFramework/Models/ParamModel.swift
Sources/MockoloFramework/Models/ParsedEntity.swift
Sources/MockoloFramework/Models/TypeAliasModel.swift
Sources/MockoloFramework/Models/VariableModel.swift
Sources/MockoloFramework/Operations/Generator.swift
Sources/MockoloFramework/Operations/ImportsHandler.swift
Sources/MockoloFramework/Operations/UniqueModelGenerator.swift
Sources/MockoloFramework/Parsers/SwiftSyntaxExtensions.swift
Sources/MockoloFramework/Templates/MethodTemplate.swift
Sources/MockoloFramework/Templates/NominalTemplate.swift
Sources/MockoloFramework/Templates/VariableTemplate.swift
Sources/MockoloFramework/Utils/FunctionSuffixTemplate.swift
Sources/MockoloFramework/Utils/InheritanceResolver.swift

There is a lot of dead code in mockolo due to historical reasons.
With many unused definitions and arguments, they make hard to understand of the code, so I would like to clean up them.
In this PR, I will make some simple deletions and replace some implementations with simpler forms

Remove dead codes

---

Sources/MockoloFramework/Models/ArgumentsHistoryModel.swift
Sources/MockoloFramework/Models/ClosureModel.swift
Sources/MockoloFramework/Models/IfMacroModel.swift
Sources/MockoloFramework/Models/MethodModel.swift
Sources/MockoloFramework/Models/Model.swift
Sources/MockoloFramework/Models/NominalModel.swift
Sources/MockoloFramework/Models/ParamModel.swift
Sources/MockoloFramework/Models/ParsedEntity.swift
Sources/MockoloFramework/Models/TypeAliasModel.swift
Sources/MockoloFramework/Models/VariableModel.swift
Sources/MockoloFramework/Operations/Generator.swift
Sources/MockoloFramework/Operations/ImportsHandler.swift
Sources/MockoloFramework/Operations/TemplateRenderer.swift
Sources/MockoloFramework/Operations/UniqueModelGenerator.swift
Sources/MockoloFramework/Parsers/SourceParser.swift
Sources/MockoloFramework/Parsers/SwiftSyntaxExtensions.swift
Sources/MockoloFramework/Templates/ClosureTemplate.swift
Sources/MockoloFramework/Templates/IfMacroTemplate.swift
Sources/MockoloFramework/Templates/MethodTemplate.swift
Sources/MockoloFramework/Templates/NominalTemplate.swift
Sources/MockoloFramework/Templates/VariableTemplate.swift
Sources/MockoloFramework/Utils/InheritanceResolver.swift
Sources/MockoloFramework/Utils/TypeParser.swift
Tests/MockoloTestCase.swift
Tests/TestMacros/FixtureMacro.swift
Tests/TestMacros/MacroTests.swift

`Model.render` has a lot of arguments, making it very complex.
There are also places where meaningless values are being passed.
In this PR, I will organize the arguments by separating them into `RenderContext` and `GenerationArguments`, allowing us to distinguish between global settings and the state during the render process.

Organize the arguments of Model.render.

---

Sources/MockoloFramework/Utils/TypeParser.swift
Tests/TestActor/FixtureActor.swift
Tests/TestActor/FixtureGlobalActor.swift
Tests/TestArgumentsHistory/FixtureArgumentsHistory.swift
Tests/TestClassMocking/FixtureMockableClass.swift
Tests/TestExistentialAny/FixtureExistentialAny.swift
Tests/TestFuncs/TestBasicFuncs/FixtureNonSimpleFuncs.swift
Tests/TestFuncs/TestBasicFuncs/FixtureSimpleFuncs.swift
Tests/TestFuncs/TestFuncAsync/FixtureFuncAsync.swift
Tests/TestFuncs/TestFuncThrow/FixtureFuncThrow.swift
Tests/TestFuncs/TestGenericFuncs/FixtureGenericFunc.swift
Tests/TestFuncs/TestOpaqueTypeFuncs/FixtureOpaqueTypeFunc.swift
Tests/TestInit/FixtureInit.swift
Tests/TestNamespaces/FixtureModuleOverrides.swift
Tests/TestNamespaces/FixtureNestedProtocol.swift
Tests/TestOverloads/FixtureDuplicates1.swift
Tests/TestOverloads/FixtureDuplicates2.swift
Tests/TestOverloads/FixtureDuplicates3.swift
Tests/TestOverloads/FixtureFuncOverload2.swift
Tests/TestOverloads/FixtureInheritance.swift
Tests/TestRx/FixtureRxVars.swift
Tests/TestSendable/FixtureSendable.swift
Tests/TestTuplesBrackets/FixtureTuplesBrackets.swift

Simple refactoring. This PR does not include functional changes.
Remove redundant tuple in handler type. 
ex: before `(Int) -> (String)`, after `(Int) -> String`

Remove redundant tuple in handler type

---

Sources/MockoloFramework/Models/IfMacroModel.swift
Sources/MockoloFramework/Parsers/SwiftSyntaxExtensions.swift
Sources/MockoloFramework/Templates/IfMacroTemplate.swift
Tests/TestMacros/FixtureMacro.swift
Tests/TestMacros/MacroTests.swift

This PR addresses #273 and performs `uniqueEntities` method for IfMacroModel before rendering because entities inside IfMacroModel are not treated as NominalModel's entities.
I think IfMacro support is insufficient yet (see #263  ) but I am focusing to fix #273 in this PR.
- Input
```swift
/// @mockable
protocol PresentableListener: AnyObject {
#if RELEASE
func run(value: Int)
func run(value: String)
#endif
}
```
- Output
<table>
<thead><tr><th>Before</th><th>After</th></tr></thead>
<tbody>
<tr><td>
```swift
class PresentableListenerMock: PresentableListener {
init() { }
#if RELEASE
private(set) var runCallCount = 0
var runHandler: ((Int) -> ())?
func run(value: Int) {
runCallCount += 1
if let runHandler = runHandler {
runHandler(value)
}
}
// not supporting overload
private(set) var …
```

Avoid duplicated variable under if-macro syntax

---

Sources/MockoloFramework/Models/ArgumentsHistoryModel.swift
Sources/MockoloFramework/Models/ClosureModel.swift
Sources/MockoloFramework/Models/MethodModel.swift
Sources/MockoloFramework/Models/Model.swift
Sources/MockoloFramework/Models/NominalModel.swift
Sources/MockoloFramework/Models/ParamModel.swift
Sources/MockoloFramework/Models/ParsedEntity.swift
Sources/MockoloFramework/Models/TypeAliasModel.swift
Sources/MockoloFramework/Models/VariableModel.swift
Sources/MockoloFramework/Operations/Generator.swift
Sources/MockoloFramework/Operations/OutputWriter.swift
Sources/MockoloFramework/Operations/UniqueModelGenerator.swift
Sources/MockoloFramework/Templates/ClosureTemplate.swift
Sources/MockoloFramework/Templates/ConcurrencyHelpersTemplate.swift
Sources/MockoloFramework/Templates/MethodTemplate.swift
Sources/MockoloFramework/Templates/NominalTemplate.swift
Sources/MockoloFramework/Templates/VariableTemplate.swift
Sources/MockoloFramework/Utils/StringExtensions.swift
Sources/MockoloFramework/Utils/TypeParser.swift
Tests/MockoloTestCase.swift
Tests/TestSendable/FixtureSendable.swift
Tests/TestSendable/SendableTests.swift

Issue: https://github.com/uber/mockolo/issues/249
When the mock protocol requires `Sendable`,  correctly implement the mock functions as `Sendable`. To provide a concurrency-safe implementation, we also add some helper functions and types.
This PR does not address stored properties or computed properties (Do it later).
As shown below, various function `Handler`s are required to be `Sendable`.
```swift
/// @mockable
protocol APIClient: Sendable {
func fetchData(_ id: AnyObject) async -> Int
}
```
```swift
final class APIClientMock: APIClient {
init() { }
private let fetchDataState = MockoloMutex(MockoloHandlerState<AnyObject, @Sendable (AnyObject) async -> Int>())
var fetchDataCallCount: Int {
return fetchDataState.withLock(\.callCount)
}
var fetchDataArgValues: [AnyObject] {
return …
```

Concurrency safe handler

---

Sources/MockoloFramework/Parsers/SwiftSyntaxExtensions.swift
Tests/TestActor/ActorTests.swift
Tests/TestActor/FixtureGlobalActor.swift

mockolo cannot detect the mock annotation in code like the following:
```swift
@MainActor
/// @mockable
protocol P {
}
```
This PR fixes this issue.

Fix undetectable mock annotations with attributes above.

---

Sources/MockoloFramework/Models/ArgumentsHistoryModel.swift
Sources/MockoloFramework/Parsers/SwiftSyntaxExtensions.swift
Sources/MockoloFramework/Templates/MethodTemplate.swift
Sources/MockoloFramework/Utils/TypeParser.swift
Tests/TestArgumentsHistory/ArgumentsHistoryTests.swift
Tests/TestArgumentsHistory/FixtureArgumentsHistory.swift
Tests/TestSendable/FixtureSendable.swift

Issue: https://github.com/uber/mockolo/issues/283
Add labels to the history property of mock function arguments.
These labels enhance the readability of the test code.
Since access by index remains possible even with the addition of labels, I believe this change does not break backward compatibility.
```swift
let t = (a: 0, b: 1)
t.0 // 0
t.a // 0
```

Add labels to history tuple array

---

Sources/MockoloFramework/Models/ClosureModel.swift
Sources/MockoloFramework/Templates/ClosureTemplate.swift
Sources/MockoloFramework/Templates/MethodTemplate.swift
Sources/MockoloFramework/Utils/TypeParser.swift

The `SwiftType` has a `cast` property, which is a temporary value used only in certain situations and need not be stored.
Remove it because it is structurally unnatural.

Remove `cast` property from `SwiftType`

---

Sources/MockoloFramework/Models/MethodModel.swift
Sources/MockoloFramework/Models/ParamModel.swift
Sources/MockoloFramework/Models/VariableModel.swift
Sources/MockoloFramework/Parsers/SwiftSyntaxExtensions.swift
Sources/MockoloFramework/Templates/ClosureTemplate.swift
Sources/MockoloFramework/Templates/MethodTemplate.swift
Sources/MockoloFramework/Templates/NominalTemplate.swift
Sources/MockoloFramework/Templates/ParamTemplate.swift
Sources/MockoloFramework/Templates/VariableTemplate.swift
Sources/MockoloFramework/Utils/StringExtensions.swift
Sources/MockoloFramework/Utils/TypeParser.swift

Fix the handling of the type name "Unknown".
Previously, using "Unknown" as a type name would trigger special treatment and lead to unintended behavior.
Stop using empty value as `SwiftType`, it has implicit behavior depending its value. Use void type when representing empty return value.

Avoid Special Handling of the "Unknown" Type Name

---

.github/workflows/builds.yml
.github/workflows/release.yml
bundle/info.json
bundle/make_artifactbundle.sh
install-script.sh

Switch release build to use Swift 6.1 and update outdated dependencies.
I have decided to stop using the Swift SDK for the following reasons:
- The static Linux SDK significantly increases the size of the output binary.
- Distributing the artifact bundle to every Linux environment is not a priority. Previously (before [#265](https://github.com/uber/mockolo/pull/265)), the artifact was only shipped to Ubuntu, and the main reason for switching to the Swift SDK was to improve build times.
- Ubuntu will continue to be the primary supported Linux distribution. Support for other distributions can be added upon request.
- We can now utilize ARM Linux machines provided by GitHub, making it straightforward and efficient to build ARM binaries.

Update CI Configuration

---

.github/workflows/release.yml

It turns out this wasn’t actually an issue, since Swift 6.1 appears to be pre-installed on the [Ubuntu 22.04 image](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md).

Fix matrix destination name in release.yml
